# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

# From https://black.readthedocs.io/en/stable/integrations/source_version_control.html
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
    -   id: black
        language_version: python3.13
        args: [-l 132]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    -   id: mypy
        args: [--allow-redefinition, --ignore-missing-imports]

-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v6.0.0
   hooks:
   -  id: check-merge-conflict
   -  id: check-toml
   -  id: check-yaml
   -  id: end-of-file-fixer
   -  id: requirements-txt-fixer
   -  id: trailing-whitespace

-  repo: https://github.com/asottile/pyupgrade
   rev: v3.21.0
   hooks:
   -  id: pyupgrade
      args: [--py310-plus]
